@startuml enlaces

[*] --> Login 
Login : clave

state ENLACE{

PROFESOR : CON RESTRICCION
SECRETARIA: ALGUNAS RESTRICCIONES
ADMNISTRACION: SIN RESTRICCIONES

}

Login --> ENLACE: se dirige a las paginas
ENLACE --> WEB

WEN-->[*]


@enduml